Database setup or configuration error: Please verify your database settings and check the logs/error.log file for detailed error messages.
java.lang.IllegalArgumentException: java.sql.SQLException: ConnectionManager.getConnection() failed to obtain a connection after 11 retries. The exception from the last attempt is as follows: org.postgresql.util.PSQLException: FATAL: database "dboj_xmpp" does not exist
	at org.jivesoftware.openfire.XMPPServer.verifyDataSource(XMPPServer.java:710)
	at org.jivesoftware.openfire.XMPPServer.start(XMPPServer.java:427)
	at org.jivesoftware.openfire.XMPPServer.<init>(XMPPServer.java:161)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
	at java.lang.Class.newInstance(Class.java:374)
	at org.jivesoftware.openfire.starter.ServerStarter.start(ServerStarter.java:106)
	at org.jivesoftware.openfire.starter.ServerStarter.main(ServerStarter.java:51)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at com.exe4j.runtime.LauncherEngine.launch(Unknown Source)
	at com.install4j.runtime.Launcher.main(Unknown Source)
Caused by: java.sql.SQLException: ConnectionManager.getConnection() failed to obtain a connection after 11 retries. The exception from the last attempt is as follows: org.postgresql.util.PSQLException: FATAL: database "dboj_xmpp" does not exist
	at org.jivesoftware.database.DbConnectionManager.getConnection(DbConnectionManager.java:124)
	at org.jivesoftware.openfire.XMPPServer.verifyDataSource(XMPPServer.java:698)
	... 15 more
Server halted
